### ISSUE TITLE
doc links and slack help all broken

### ISSUE THREAD

**Issue by plockaby** [GetDKAN/dkan#3096]
Hello! I'd love to try installing dkan2 but I'm running into the following issues:

1. The link on the release announcement to "https://docs.getdkan.com/" goes to a page that says "page not found".
2. On the resources page (see: https://getdkan.org/resources) the link to "Documentation" goes to the same "page not found".
3. On the resources page the link to "Roadmap" just goes to the same page so I'm not sure if there even is a roadmap.
4. On the medium post about the release (see: https://medium.com/dkan-blog/dkan-v2-is-here-aee0acf69c1e) it says that I can join dkan.slack.com to ask questions but that only lets me join if I create an account and I can only create an account if I "have an @state.ca.gov, @library.ca.gov, or @govops.ca.gov email address".
5. Your demo is broken on this page: https://demo.getdkan.com/api -- it says "Failed to fetch http://dkan/api/1"
6. I installed DKAN 1.18 about a month ago and it was fairly easy. I just dropped it onto my file system and it worked. The installation for Dkan2 is apparently quite different and there are no instructions that I can find anywhere for actually installing it.

I guess the issue here is that there are a lot of broken links and the documentation for doing an installation is nowhere to be found. Is there documentation?

**Comment by janette** [comment]
@plockaby 

- Docs: Thank you for the feedback, the docs have been restored so the links should work now. 
- Roadmap: this is not quite ready yet, hope to have a rough draft out soon. 
- Slack: you should be able to create an account with any email, try https://dkansignup.herokuapp.com/
- API page: mmm, looking into that
- Installation: this should be easy if using [DKAN Tools](https://github.com/getdkan/dkan-tools), v2 is simply modules now rather than a profile, so if you don't want to use docker and the DKAN tools commands you could just stand up a Drupal 8 site and add the dkan modules. https://demo.getdkan.com/modules/contrib/dkan/docs/installation.html

**Comment by janette** [comment]
@plockaby 
the API page is working now, it is important to update the `.env.production` file with the correct url 😄

**Comment by plockaby** [comment]
Thanks! Those were the pointers that I needed. I appreciate you fixing the links and now the docs.getdkan.org page has what I mostly need on it. Appreciated.

**Comment by plockaby** [comment]
Would it be possible to explain how you solved the API page problem? I am having the same issue. I've updated my `.env.production` file and restarted the containers but I'm still seeing the same error.

**Comment by plockaby** [comment]
Additionally, I don't see this in the documentation but how do I tell DKAN that it is being proxied? It keeps trying to redirect to port 8443. I have haproxy(443) -> apache(8443) -> dkan(32780).

**Comment by janette** [comment]
@plockaby it is in the DKAN Tools README file: https://github.com/GetDKAN/dkan-tools#setup-and-start-the-proxy

If you get the 'dkan' proxy working then you won't need to edit the .env.production file, this makes it easy to do development work locally.

If you are trying to get the build working on a production server that is when you would edit the `src/frontend/.env.production` file so that the GATSBY_API_URL value is the url of your prod site.

**Comment by fmizzell** [comment]
@plockaby Now that the links are working, I am going to close this ticket. Hopefully we will see you on slack.

**Comment by plockaby** [comment]
Unfortunately neither of those solutions solved my problem with proxying. I'll consider getting onto the slack channel. I always hesitate to creating new accounts for a single, short-lived purpose. Thanks again.

**Comment by janette** [comment]
@plockaby did you do this step `docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy`

**Comment by plockaby** [comment]
I did try that at one point but it did not find the nginx instance in docker and besides I wanted SSL termination. What I am running right now is HAProxy as my SSL terminator with Apache in front of that to do proxying and authentication into the docker container that actually runs DKAN. However, the DKAN API is certain that its URL is http://dkan/ even though I've changed .env.production and .env.development and restarted all of the containers and further dkan thinks that it is running on port 8443 (instead of 443) whenever it does a redirect and I do not know how to change that.

**Comment by mitthuzyxware** [comment]
Hi,
I am working with DKAN in Drupal 10.
I have tried the https://dkansignup.herokuapp.com/ for dkan community on sclak. But this page saying "There's nothing here, yet.".
Is the signup to DKAN slack link has changed?

**Comment by dafeder** [comment]
Hi @mitthuzyxware, we are moving away from Slack as a community support tool, please use the [github discussions](https://github.com/GetDKAN/dkan/discussions) for this repo to ask questions, make suggestions etc. Thanks!

**Comment by mitthuzyxware** [comment]
Thanks @dafeder for information.
